name: Update Gauge Data

on:
  schedule:
    - cron: '15 * * * *'  # every hour at the top of the hour (UTC)
  workflow_dispatch:      # manual trigger if needed

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    env:
      HYDROVU_CLIENT_ID: ${{ secrets.HYDROVU_CLIENT_ID }}
      HYDROVU_CLIENT_SECRET: ${{ secrets.HYDROVU_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
           Rscript -e 'install.packages(c("httr2","httr", "jsonlite", "tidyverse", "curl"))'

      - name: Run the script
        run: Rscript Hourly_Updater.R

# Commit and push updated CSV files if there are changes
      - name: Commit updated results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .  # Add all changes (adjust if necessary)
          git diff --cached --exit-code || git commit -m "Update gauge data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
