name: Update Gauge Data

on:
  schedule:
    - cron: '15 * * * *'  # Every hour at 15 minutes past
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    env:
      HYDROVU_CLIENT_ID: ${{ secrets.HYDROVU_CLIENT_ID }}
      HYDROVU_CLIENT_SECRET: ${{ secrets.HYDROVU_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("httr2", "jsonlite"), repos = "https://cloud.r-project.org", dependencies = TRUE)'

      - name: Run update script
        run: Rscript Hourly_Updater.R

      - name: Commit updated results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase || true  # Avoid push errors if remote has changed
          git add .
          git diff --cached --quiet || git commit -m "Update gauge data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
